<a href="https://colab.research.google.com/github/Mangethe/Colab/blob/master/Classification_Hackathon_Shabangu.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
# Import some libraries we will need
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from collections import Counter
%matplotlib inline

from pylab import rcParams

rcParams['figure.figsize'] = 10, 8
sns.set_style('whitegrid')

import sklearn
from sklearn import preprocessing
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn import metrics
from sklearn.metrics import classification_report

import nltk
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer

import string
from string import digits

import plotly.offline as py
import plotly.graph_objs as go

In [136]:
sub = pd.read_csv('sample_submission.csv')
sub.head()

TransactionId  FraudResult
0  TransactionId_50600          NaN
1  TransactionId_95109          NaN
2  TransactionId_47357          NaN
3  TransactionId_28185          NaN
4  TransactionId_22140          NaN

In [137]:
sub.shape

(45019, 2)

In [138]:
train = pd.read_csv('training.csv')
train.head()

TransactionId         BatchId  ... PricingStrategy FraudResult
0  TransactionId_76871   BatchId_36123  ...               2           0
1  TransactionId_73770   BatchId_15642  ...               2           0
2  TransactionId_26203   BatchId_53941  ...               2           0
3    TransactionId_380  BatchId_102363  ...               2           0
4  TransactionId_28195   BatchId_38780  ...               2           0

[5 rows x 16 columns]

In [139]:
train.isnull().sum()

TransactionId           0
BatchId                 0
AccountId               0
SubscriptionId          0
CustomerId              0
CurrencyCode            0
CountryCode             0
ProviderId              0
ProductId               0
ProductCategory         0
ChannelId               0
Amount                  0
Value                   0
TransactionStartTime    0
PricingStrategy         0
FraudResult             0
dtype: int64

In [140]:
train.describe()

CountryCode        Amount         Value  PricingStrategy   FraudResult
count      95662.0  9.566200e+04  9.566200e+04     95662.000000  95662.000000
mean         256.0  6.717846e+03  9.900584e+03         2.255974      0.002018
std            0.0  1.233068e+05  1.231221e+05         0.732924      0.044872
min          256.0 -1.000000e+06  2.000000e+00         0.000000      0.000000
25%          256.0 -5.000000e+01  2.750000e+02         2.000000      0.000000
50%          256.0  1.000000e+03  1.000000e+03         2.000000      0.000000
75%          256.0  2.800000e+03  5.000000e+03         2.000000      0.000000
max          256.0  9.880000e+06  9.880000e+06         4.000000      1.000000

In [141]:
train.columns

Index(['TransactionId', 'BatchId', 'AccountId', 'SubscriptionId', 'CustomerId',
       'CurrencyCode', 'CountryCode', 'ProviderId', 'ProductId',
       'ProductCategory', 'ChannelId', 'Amount', 'Value',
       'TransactionStartTime', 'PricingStrategy', 'FraudResult'],
      dtype='object')

In [142]:
train.index

RangeIndex(start=0, stop=95662, step=1)

In [0]:
X = train.drop(['ProviderId','CustomerId','TransactionId', 'BatchId', 'AccountId','FraudResult','ProductId','ChannelId', 'SubscriptionId', 'CurrencyCode','TransactionStartTime'], axis = 1)
y = train['FraudResult']

In [193]:
train.groupby('CustomerId').sum().drop('PricingStrategy', axis = 1).head()

CountryCode   Amount  Value  FraudResult
CustomerId                                               
CustomerId_1             256 -10000.0  10000            0
CustomerId_10            256 -10000.0  10000            0
CustomerId_1001         1280  20000.0  30400            0
CustomerId_1002         2816   4225.0   4775            0
CustomerId_1003         1536  20000.0  32000            0

In [194]:
X.isnull().sum()

CustomerId         0
CountryCode        0
ProductCategory    0
Amount             0
Value              0
PricingStrategy    0
dtype: int64

In [218]:
y = train[['FraudResult']]
y.head()

FraudResult
0            0
1            0
2            0
3            0
4            0

In [219]:
XX = pd.get_dummies(X, drop_first=True)
XX.head()

CountryCode   Amount  ...  ProductCategory_tv  ProductCategory_utility_bill
0          256   1000.0  ...                   0                             0
1          256    -20.0  ...                   0                             0
2          256    500.0  ...                   0                             0
3          256  20000.0  ...                   0                             1
4          256   -644.0  ...                   0                             0

[5 rows x 12 columns]

In [0]:
X_train, X_test, y_train, y_test= train_test_split(XX, y, test_size=0.2, random_state=14)

**LogRegression**

In [0]:
LRmodel = LogisticRegression()

In [222]:
LRmodel.fit(X_train, y_train)

/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/logistic.py:432: FutureWarning:

Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.

/usr/local/lib/python3.6/dist-packages/sklearn/utils/validation.py:724: DataConversionWarning:

A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().



LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=None, solver='warn', tol=0.0001, verbose=0,
                   warm_start=False)

In [0]:
y_pred_test = LRmodel.predict(X_test)

In [224]:
y_pred_test

array([0, 0, 0, ..., 0, 0, 0])

In [225]:
from sklearn import metrics

print('Accuracy: '+ str(metrics.accuracy_score(y_test, y_pred_test)))
print('Precision: '+ str( metrics.precision_score(y_test, y_pred_test, average='macro')))
print('Recall: '+ str(metrics.recall_score(y_test, y_pred_test, average='macro')))
print('F1_Score: '+ str( metrics.f1_score(y_test, y_pred_test, average='macro')))

Accuracy: 0.9980661684001464
Precision: 0.8087651238812813
Recall: 0.6545523819501087
F1_Score: 0.7058649511859992


In [226]:
metrics.r2_score(y_test, y_pred_test)

0.11710953303850469

In [227]:
#Test:


test = pd.read_csv('test.csv')
test.head()

TransactionId        BatchId  ...  TransactionStartTime PricingStrategy
0  TransactionId_50600  BatchId_35028  ...  2019-02-13T10:01:40Z               4
1  TransactionId_95109  BatchId_45139  ...  2019-02-13T10:02:12Z               2
2  TransactionId_47357  BatchId_74887  ...  2019-02-13T10:02:30Z               2
3  TransactionId_28185  BatchId_11025  ...  2019-02-13T10:02:38Z               4
4  TransactionId_22140  BatchId_29804  ...  2019-02-13T10:02:58Z               2

[5 rows x 15 columns]

In [228]:
Test = test.drop(['ProviderId','CustomerId','TransactionId', 'BatchId', 'AccountId','ProductId','ChannelId', 'SubscriptionId', 'CurrencyCode','TransactionStartTime'], axis = 1)
Test.head()

CountryCode     ProductCategory  Amount  Value  PricingStrategy
0          256             airtime  1000.0   1000                4
1          256  financial_services  2000.0   2000                2
2          256  financial_services   -50.0     50                2
3          256             airtime  3000.0   3000                4
4          256  financial_services   -60.0     60                2

In [229]:
Test = pd.get_dummies(Test, drop_first=True)
Test.head()

CountryCode  Amount  ...  ProductCategory_tv  ProductCategory_utility_bill
0          256  1000.0  ...                   0                             0
1          256  2000.0  ...                   0                             0
2          256   -50.0  ...                   0                             0
3          256  3000.0  ...                   0                             0
4          256   -60.0  ...                   0                             0

[5 rows x 12 columns]

In [230]:
Test_pred = LRmodel.predict(Test)
Test_pred

array([0, 0, 0, ..., 0, 0, 0])

In [231]:
test['FraudResult'] = Test_pred
test.head()

TransactionId        BatchId  ... PricingStrategy FraudResult
0  TransactionId_50600  BatchId_35028  ...               4           0
1  TransactionId_95109  BatchId_45139  ...               2           0
2  TransactionId_47357  BatchId_74887  ...               2           0
3  TransactionId_28185  BatchId_11025  ...               4           0
4  TransactionId_22140  BatchId_29804  ...               2           0

[5 rows x 16 columns]

In [232]:
df_LogReg = pd.DataFrame({"TransactionId":test['TransactionId'], "FraudResult":test['FraudResult']})
df_LogReg.head()

TransactionId  FraudResult
0  TransactionId_50600            0
1  TransactionId_95109            0
2  TransactionId_47357            0
3  TransactionId_28185            0
4  TransactionId_22140            0

In [0]:
df_LogReg.to_csv('Attemptx.csv', index = False) # score 0.528301886792453

In [0]:
# Handling Imbalanced Datasets: 

In [130]:
from imblearn.over_sampling import SMOTE 

X_train_s, X_test_s, y_train_s, y_test_s = train_test_split(XX, y, test_size=0.2, random_state=42)

sm = SMOTE(random_state=42, ratio = 1.0)
X_train_s, y_train_s = sm.fit_resample(X_train_s,y_train_s)
# X_res = pd.DataFrame(data = X_res, columns = XX.columns )
# y_res = pd.DataFrame(data = y_res, columns =y.columns )


/usr/local/lib/python3.6/dist-packages/sklearn/utils/validation.py:724: DataConversionWarning:

A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().



In [0]:
LRmodel_s = LogisticRegression()

In [132]:
LRmodel_s.fit(X_train_s, y_train_s)

/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/logistic.py:432: FutureWarning:

Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.



LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=None, solver='warn', tol=0.0001, verbose=0,
                   warm_start=False)

In [133]:
y_pred_res = LRmodel.predict(X_test_s)
y_pred_res

array([0, 0, 0, ..., 0, 0, 0])

In [134]:
print('Accuracy: '+ str(metrics.accuracy_score(y_test_s, y_pred_res)))
print('Precision: '+ str( metrics.precision_score(y_test_s, y_pred_res)))
print('Recall: '+ str(metrics.recall_score(y_test_s, y_pred_res)))
print('F1_Score: '+ str( metrics.f1_score(y_test_s, y_pred_res)))

Accuracy: 0.9982229655568913
Precision: 0.5625
Recall: 0.25
F1_Score: 0.34615384615384615


In [135]:
metrics.r2_score(y_test_s, y_pred_res)

0.05377517120199271

In [0]:
#OR:

In [106]:
from sklearn.utils import resample
# setting up testing and training sets
X_train_a, X_test_a, y_train_a, y_test_a = train_test_split(XX, y, test_size=0.2, random_state=42)

# concatenate our training data back together
F = pd.concat([X_train_a, y_train_a], axis=1)


# separate minority and majority classes
not_fraud =F[F.FraudResult==0]
fraud =F[F.FraudResult==1]


# upsample minority
fraud_upsampled = resample(fraud,
                          replace=True, # sample with replacement
                          n_samples=len(not_fraud), # match number in majority class
                          random_state=42) # reproducible results

upsampled = pd.concat([not_fraud, fraud_upsampled])

upsampled.FraudResult.value_counts()

1    76372
0    76372
Name: FraudResult, dtype: int64

In [113]:
upsampled.head()

CountryCode   Amount  ...  ProductCategory_utility_bill  FraudResult
59096          256   -100.0  ...                             0            0
35991          256   5000.0  ...                             0            0
69457          256   1000.0  ...                             0            0
58498          256    -70.0  ...                             0            0
88790          256  20000.0  ...                             0            0

[5 rows x 13 columns]

In [0]:
y_train_aa = upsampled.FraudResult
X_train_aa = upsampled.drop('FraudResult', axis=1)

In [0]:
LRmodel_a = LogisticRegression()

In [117]:
LRmodel_a.fit(X_train_aa, y_train_aa)

/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/logistic.py:432: FutureWarning:

Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.



LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=None, solver='warn', tol=0.0001, verbose=0,
                   warm_start=False)

In [120]:
y_pred_a = LRmodel_a.predict(X_test_a)
y_pred_a

array([0, 0, 0, ..., 0, 0, 0])

In [121]:
print('Accuracy: '+ str(metrics.accuracy_score(y_test_a, y_pred_a)))
print('Precision: '+ str( metrics.precision_score(y_test_a, y_pred_a)))
print('Recall: '+ str(metrics.recall_score(y_test_a, y_pred_a)))
print('F1_Score: '+ str( metrics.f1_score(y_test_a, y_pred_a)))

Accuracy: 0.9905921705953066
Precision: 0.16666666666666666
Recall: 1.0
F1_Score: 0.2857142857142857


In [122]:
metrics.r2_score(y_test_a, y_pred_a)

-4.0094255642247445

In [123]:
#OR:

# still using our separated classes fraud and not_fraud from above

# downsample majority
not_fraud_downsampled = resample(not_fraud,
                                replace = False, # sample without replacement
                                n_samples = len(fraud), # match minority n
                                random_state = 27) # reproducible results

downsampled = pd.concat([not_fraud_downsampled, fraud])

downsampled.FraudResult.value_counts()

1    157
0    157
Name: FraudResult, dtype: int64

In [0]:
y_train_bb = downsampled.FraudResult
X_train_bb = downsampled.drop('FraudResult', axis=1)

In [0]:
LRmodel_b = LogisticRegression()

In [126]:
LRmodel_b.fit(X_train_bb, y_train_bb)

/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/logistic.py:432: FutureWarning:

Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.



LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=None, solver='warn', tol=0.0001, verbose=0,
                   warm_start=False)

In [127]:
y_pred_b = LRmodel_b.predict(X_test_a)
y_pred_b

array([0, 0, 0, ..., 0, 0, 0])

In [128]:
print('Accuracy: '+ str(metrics.accuracy_score(y_test_a, y_pred_b)))
print('Precision: '+ str( metrics.precision_score(y_test_a, y_pred_b)))
print('Recall: '+ str(metrics.recall_score(y_test_a, y_pred_b)))
print('F1_Score: '+ str( metrics.f1_score(y_test_a, y_pred_b)))

Accuracy: 0.9895468562170072
Precision: 0.15254237288135594
Recall: 1.0
F1_Score: 0.2647058823529412


In [129]:
metrics.r2_score(y_test_a, y_pred_b)

-4.56602840469416

**RandomForestClassifier**

In [0]:
X_train_r, X_test_r, y_train_r, y_test_r= train_test_split(XX, y, test_size=0.2, random_state=42)

In [0]:
from sklearn.ensemble import RandomForestClassifier

RFC = RandomForestClassifier(n_estimators=100, max_depth=2,random_state=0)

In [236]:
RFC.fit(X_train_r, y_train_r)

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: DataConversionWarning:

A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().



RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
                       max_depth=2, max_features='auto', max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=100,
                       n_jobs=None, oob_score=False, random_state=0, verbose=0,
                       warm_start=False)

In [0]:
y_pred_r = RFC.predict(X_test_r)

In [241]:
from sklearn import metrics

print('Accuracy: '+ str(metrics.accuracy_score(y_test_r, y_pred_r)))
print('Precision: '+ str( metrics.precision_score(y_test_r, y_pred_r, average='macro')))
print('Recall: '+ str(metrics.recall_score(y_test_r, y_pred_r, average='macro')))
print('F1_Score: '+ str( metrics.f1_score(y_test_r, y_pred_r, average='macro')))
print('R-squared: '+ str(metrics.r2_score(y_test_r, y_pred_r)))

Accuracy: 0.9994250770919354
Precision: 0.9023604574512119
Recall: 0.9581238763505612
F1_Score: 0.9284274080419567
R-squared: 0.6938684377418212


In [0]:
Test_pred_r = RFC.predict(Test)

In [243]:
Test_pred_r

array([0, 0, 0, ..., 0, 0, 0])

In [244]:
df_LogReg_2 = pd.DataFrame({"TransactionId":test['TransactionId'], "FraudResult":Test_pred_r})
df_LogReg_2.head()

TransactionId  FraudResult
0  TransactionId_50600            0
1  TransactionId_95109            0
2  TransactionId_47357            0
3  TransactionId_28185            0
4  TransactionId_22140            0

In [0]:
df_LogReg_2.to_csv('Attempt1_random.csv', index = False) # score: 0.685714285714286

In [0]:
RFC = RandomForestClassifier(n_estimators=100, max_depth=2,random_state=42)

In [247]:
RFC.fit(X_train_r, y_train_r)

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: DataConversionWarning:

A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().



RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
                       max_depth=2, max_features='auto', max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=100,
                       n_jobs=None, oob_score=False, random_state=42, verbose=0,
                       warm_start=False)

In [0]:
y_pred_r = RFC.predict(X_test_r)

In [249]:
print('Accuracy: '+ str(metrics.accuracy_score(y_test_r, y_pred_r)))
print('Precision: '+ str( metrics.precision_score(y_test_r, y_pred_r, average='macro')))
print('Recall: '+ str(metrics.recall_score(y_test_r, y_pred_r, average='macro')))
print('F1_Score: '+ str( metrics.f1_score(y_test_r, y_pred_r, average='macro')))
print('R-squared: '+ str(metrics.r2_score(y_test_r, y_pred_r)))

Accuracy: 0.9994773428108503
Precision: 0.8977010796317727
Recall: 0.9858754720054924
F1_Score: 0.9373690619598807
R-squared: 0.721698579765292


In [0]:
Test_pred_r = RFC.predict(Test)

In [252]:
df_LogReg_3 = pd.DataFrame({"TransactionId":test['TransactionId'], "FraudResult":Test_pred_r})
df_LogReg_3.head()

TransactionId  FraudResult
0  TransactionId_50600            0
1  TransactionId_95109            0
2  TransactionId_47357            0
3  TransactionId_28185            0
4  TransactionId_22140            0

In [0]:
df_LogReg_3.to_csv('Attempt2_random.csv', index = False) # score: 0.704225352112676

In [254]:
RFC.fit(X_train_s,y_train_s)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
                       max_depth=2, max_features='auto', max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=100,
                       n_jobs=None, oob_score=False, random_state=42, verbose=0,
                       warm_start=False)

In [256]:
ypred_s = RFC.predict(X_test_s)
ypred_s

array([0, 0, 0, ..., 0, 0, 0])

In [257]:
print('Accuracy: '+ str(metrics.accuracy_score(y_test_s, ypred_s)))
print('Precision: '+ str( metrics.precision_score(y_test_s, ypred_s)))
print('Recall: '+ str(metrics.recall_score(y_test_s, ypred_s)))
print('F1_Score: '+ str( metrics.f1_score(y_test_s, ypred_s)))

Accuracy: 0.9811320754716981
Precision: 0.0906801007556675
Recall: 1.0
F1_Score: 0.16628175519630484


**DecisionTreeClassifier**

In [0]:
X_train_d, X_test_d, y_train_d, y_test_d= train_test_split(XX, y, test_size=0.2, random_state=42)

In [0]:
from sklearn.tree import DecisionTreeClassifier

DTmodel = DecisionTreeClassifier(random_state=42)

In [260]:
DTmodel.fit(X_train_d, y_train_d)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
                       max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort=False,
                       random_state=42, splitter='best')

In [0]:
y_pred_d = DTmodel.predict(X_test_d)

In [262]:
print('Accuracy: '+ str(metrics.accuracy_score(y_test_d, y_pred_d)))
print('Precision: '+ str( metrics.precision_score(y_test_d, y_pred_d, average='macro')))
print('Recall: '+ str(metrics.recall_score(y_test_d, y_pred_d, average='macro')))
print('F1_Score: '+ str( metrics.f1_score(y_test_d, y_pred_d, average='macro')))
print('R-squared: '+ str(metrics.r2_score(y_test_d, y_pred_d)))

Accuracy: 0.9998432028432551
Precision: 0.9999214659685864
Recall: 0.9583333333333333
F1_Score: 0.9782215994654713
R-squared: 0.9165095739295877


In [0]:
Test_pred_d = DTmodel.predict(Test)

In [264]:
df_LogReg_d = pd.DataFrame({"TransactionId":test['TransactionId'], "FraudResult":Test_pred_d})
df_LogReg_d.head()

TransactionId  FraudResult
0  TransactionId_50600            0
1  TransactionId_95109            0
2  TransactionId_47357            0
3  TransactionId_28185            0
4  TransactionId_22140            0

In [265]:
df_LogReg_d.shape

(45019, 2)

In [0]:
df_LogReg_3.to_csv('Attempt1_dt.csv', index = False) # score: 0.679245283018868